name: checksum

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
            hash-type: md5
            get-assets: true
            file-name: md5.txt
      - uses: actions/upload-artifact@v2
        with:
            name: Asset Hashes
            path: md5.txt
